### ISSUE TITLE
Insomnia is not able to recognize mac's environment variables

### ISSUE THREAD

**Issue by nickchow0112** [etauker/insomnia-plugin-system-env#1]
Hi, I added some env variables on my mac, but the plugin is not able to pick up these variables.

<img width="487" alt="Screen Shot 2020-03-31 at 1 51 11 PM" src="https://user-images.githubusercontent.com/16962066/78074034-cfdd7400-7356-11ea-964c-1ebc66a2ab94.png">
<img width="781" alt="Screen Shot 2020-03-31 at 1 51 27 PM" src="https://user-images.githubusercontent.com/16962066/78074038-d23fce00-7356-11ea-8e67-50ed1ee6c204.png">

**Comment by etauker** [comment]
Hi @nickchow0112,
How did you open insomnia? The insomnia instance needs to be opened from the same terminal in which you exported the token, for example:
```
STAGING_API_TOKEN=3fc345d2-9dd8-48e8-a178-3c91c867cc41 /Applications/Insomnia.app/Contents/MacOS/Insomnia
```

I also updated the example in the readme.

**Comment by nickchow0112** [comment]
Hi @etauker, I actually tried example 1 instead of 2. But it wasn't able to pick up the environment variables.I just tried your second method and it works! thanks!

**Comment by gelato-piotr-rozmarynowski** [comment]
Hi @etauker. 
I have added custom variables to my `~/.zshrc` and `~/.bash_profile`. They are output correctly when executing `env` command. But unfortunately, Insomnia cannot fetch them, only when I run the app through the terminal.
Is there a way to run Insomnia using mac UI instead of the terminal command to have the environment variables automatically loaded? 
Thanks!
